-- MySQL Script generated by MySQL Workbench
-- Fri May  7 18:01:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WaffleDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WaffleDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WaffleDB` DEFAULT CHARACTER SET utf8 ;
USE `WaffleDB` ;

-- -----------------------------------------------------
-- Table `WaffleDB`.`Addition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Addition` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Addition` (
  `idAddition` INT NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`idAddition`),
  CONSTRAINT `fk_Addition_Product1`
    FOREIGN KEY (`idAddition`)
    REFERENCES `WaffleDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Addition_Product1_idx` ON `WaffleDB`.`Addition` (`idAddition` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Ingredient` (
  `idIngredient` INT NOT NULL,
  `idNuIn` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `price` FLOAT NULL,
  `processingTimeSec` INT NOT NULL,
  PRIMARY KEY (`idIngredient`),
  CONSTRAINT `fk_Ingredient_NutritionalInformation1`
    FOREIGN KEY (`idNuIn`)
    REFERENCES `WaffleDB`.`NutritionalInformation` (`idNuIn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ingredient_NutritionalInformation1_idx` ON `WaffleDB`.`Ingredient` (`idNuIn` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Inventory` (
  `idIngredient` INT NOT NULL,
  `idStore` INT NOT NULL,
  `expiryDate` DATE NULL,
  `deliveryDate` DATE NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`idIngredient`, `idStore`),
  CONSTRAINT `fk_Inventory_Ingredient`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `WaffleDB`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Store1`
    FOREIGN KEY (`idStore`)
    REFERENCES `WaffleDB`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inventory_Store1_idx` ON `WaffleDB`.`Inventory` (`idStore` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`NutritionalInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`NutritionalInformation` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`NutritionalInformation` (
  `idNuIn` INT NOT NULL,
  `calories` FLOAT NULL,
  `saturatedFat` FLOAT NULL,
  `transFat` FLOAT NULL,
  `carbohydrates` FLOAT NULL,
  `sugar` FLOAT NULL,
  `protein` FLOAT NULL,
  `salt` FLOAT NULL,
  PRIMARY KEY (`idNuIn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Order` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Order` (
  `idOrder` INT NOT NULL,
  `idStore` INT NOT NULL,
  `totalAmount` DOUBLE NULL,
  `paymentStatus` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idOrder`),
  CONSTRAINT `fk_Order_Store1`
    FOREIGN KEY (`idStore`)
    REFERENCES `WaffleDB`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Order_Store1_idx` ON `WaffleDB`.`Order` (`idStore` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Product` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Product` (
  `idProduct` INT NOT NULL,
  `idNuIn` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `fk_Product_NutritionalInformation1`
    FOREIGN KEY (`idNuIn`)
    REFERENCES `WaffleDB`.`NutritionalInformation` (`idNuIn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Product_NutritionalInformation1_idx` ON `WaffleDB`.`Product` (`idNuIn` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`ProductOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`ProductOrder` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`ProductOrder` (
  `idOrder` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`idOrder`, `idProduct`),
  CONSTRAINT `fk_ProductOrder_Order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `WaffleDB`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductOrder_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `WaffleDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProductOrder_Order1_idx` ON `WaffleDB`.`ProductOrder` (`idOrder` ASC) VISIBLE;

CREATE INDEX `fk_ProductOrder_Product1_idx` ON `WaffleDB`.`ProductOrder` (`idProduct` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Store` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Store` (
  `idStore` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `areaCode` VARCHAR(15) NULL,
  `location` VARCHAR(255) NULL,
  `streetName` VARCHAR(255) NULL,
  `houseNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idStore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaffleDB`.`Waffle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`Waffle` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`Waffle` (
  `idWaffle` INT NOT NULL,
  `creatorName` VARCHAR(255) NULL,
  `creationDate` DATE NOT NULL,
  `processingTimeSec` INT NOT NULL,
  PRIMARY KEY (`idWaffle`),
  CONSTRAINT `fk_Waffle_Product1`
    FOREIGN KEY (`idWaffle`)
    REFERENCES `WaffleDB`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Waffle_Product1_idx` ON `WaffleDB`.`Waffle` (`idWaffle` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `WaffleDB`.`WaffleIngredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`WaffleIngredient` ;

CREATE TABLE IF NOT EXISTS `WaffleDB`.`WaffleIngredient` (
  `idIngredient` INT NOT NULL,
  `idWaffle` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`idIngredient`, `idWaffle`),
  CONSTRAINT `fk_WaffleRecept_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `WaffleDB`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WaffleRecept_Waffle1`
    FOREIGN KEY (`idWaffle`)
    REFERENCES `WaffleDB`.`Waffle` (`idWaffle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_WaffleRecept_Ingredient1_idx` ON `WaffleDB`.`WaffleIngredient` (`idIngredient` ASC) VISIBLE;

CREATE INDEX `fk_WaffleRecept_Waffle1_idx` ON `WaffleDB`.`WaffleIngredient` (`idWaffle` ASC) VISIBLE;

USE `WaffleDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `WaffleDB`.`WaffleConstruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WaffleDB`.`WaffleConstruction` (`name` INT, `price` INT, `amount` INT, `unit` INT);

-- -----------------------------------------------------
-- Placeholder table for view `WaffleDB`.`IngredientOverview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WaffleDB`.`IngredientOverview` (`name` INT, `sum(Inventory.amount)` INT, `unit` INT);

-- -----------------------------------------------------
-- View `WaffleDB`.`WaffleConstruction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`WaffleConstruction`;
DROP VIEW IF EXISTS `WaffleDB`.`WaffleConstruction` ;
USE `WaffleDB`;
CREATE  OR REPLACE VIEW `WaffleConstruction` AS
SELECT Product.name, Product.price, Ingredient.name ,WaffleIngredient.amount, Ingredient.unit FROM Product
Inner join Waffle on
	Waffle.idWaffle = Product.idProduct
Inner join WaffleIngredient on
	Waffle.idWaffle = WaffleIngredient.idWaffle
Inner join Ingredient on
	WaffleIngredient.idIngredient = Ingredient.idIngredient
order by Product.name
;

-- -----------------------------------------------------
-- View `WaffleDB`.`IngredientOverview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaffleDB`.`IngredientOverview`;
DROP VIEW IF EXISTS `WaffleDB`.`IngredientOverview` ;
USE `WaffleDB`;
CREATE  OR REPLACE VIEW `IngredientOverview` AS
select Ingredient.name, sum(Inventory.amount), Ingredient.unit, Store.name from Ingredient
left join Inventory on
	Ingredient.idIngredient = Inventory.idIngredient
inner join Store on
	Store.idStore = Inventory.idStore
Where Inventory.expiryDate < curdate()
group by Inventory.idStore, Inventory.name
order by Ingredient.name;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
